name: Sync index.html

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy file
        run: |
          cp index.html bin/weapon-url-opener

      - name: Debug - Check Git Status
        run: git status

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add bin/weapon-url-opener
          git commit -m "Sync index.html to bin/weapon-url-opener" || echo "No changes to commit"
          git push
